steps:
      - uses: actions/checkout@v4
      
      # 1. Install your project dependencies first
      - name: Install Dependencies
        run: npm ci
        
      # 2. Now run the build
      - name: Build Project
        run: npm run build
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEGAL_AID_802E }}
          channelId: live
          projectId: legal-aid-802e